## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [2]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [3]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [10]:
from sklearn.model_selection import train_test_split

y1_index = np.where(y==1)
y0_index = np.where(y==0)

In [11]:
y0_index

(array([ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,
        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199], dtype=int64),)

In [14]:
#個切10筆
train_xy1,test_xy1,train_yy1,testyy1 = train_test_split(X[y1_index],y[y1_index],test_size =10)
train_xy0,test_xy0,train_yy0,testyy0 = train_test_split(X[y0_index],y[y0_index],test_size =10)

In [15]:
train_X,train_Y = np.concatenate([train_xy1,train_xy0]),np.concatenate([train_yy1,train_yy0])
teat_X,test_Y = np.concatenate([test_xy1,test_xy0]),np.concatenate([testyy1,testyy0])


In [17]:
teat_X

array([[115, 116, 117, 118, 119],
       [ 75,  76,  77,  78,  79],
       [195, 196, 197, 198, 199],
       [ 45,  46,  47,  48,  49],
       [ 85,  86,  87,  88,  89],
       [ 95,  96,  97,  98,  99],
       [ 80,  81,  82,  83,  84],
       [100, 101, 102, 103, 104],
       [ 55,  56,  57,  58,  59],
       [150, 151, 152, 153, 154],
       [880, 881, 882, 883, 884],
       [490, 491, 492, 493, 494],
       [825, 826, 827, 828, 829],
       [395, 396, 397, 398, 399],
       [555, 556, 557, 558, 559],
       [425, 426, 427, 428, 429],
       [450, 451, 452, 453, 454],
       [475, 476, 477, 478, 479],
       [515, 516, 517, 518, 519],
       [910, 911, 912, 913, 914]])